import: Berkeley DB 5.1.29 (2011-10-25)
Upstream source tarball db-5.1.29.tar.gz imported verbatim.

diff --git a/dist/buildpkg b/dist/buildpkg
--- a/dist/buildpkg
+++ b/dist/buildpkg
@@ -1,8 +1,44 @@
 #!/bin/sh
 # $Id: $
 #
+die()
+{
+	echo >&2 "$@"
+	exit 1
+}
+
 # Build the distribution package.
-. ./RELEASE || exit 1
+. ./RELEASE || die "Can't read the RELEASE file"
+
+CSHARP_DOC_SRC=""
+# 0 is none, 1 is local dir, 2 is remote dir
+CSHARP_DOC_LOCATION=0
+
+while [ $# -gt 0 ]
+do
+	case "$1" in
+	-n)
+		nodocs=true;;
+	-csharp_doc_src)
+		shift
+		if [ ! $# -gt 0 ]; then
+	       		die "csharp_doc_dir param requires argument."
+		fi
+		CSHARP_DOC_SRC=$1
+		CSHARP_DOC_LOCATION=1
+		if [ ! -f $CSHARP_DOC_SRC ]; then
+			die "CSharp doc archive must exist."
+		fi;;
+	-csharp_doc_url)
+		shift
+		if [ ! $# -gt 0 ]; then
+	       		die "csharp_doc_dir param requires argument."
+		fi
+		CSHARP_DOC_SRC=$1
+		CSHARP_DOC_LOCATION=2;;
+	esac
+	shift
+done
 
 # A version string can be specified on the command line (e.g., "20080219").
 # Otherwise, use the standard X.X.X format.
@@ -17,30 +53,13 @@ D=`pwd`/../release
 R="$D/db-${VERSION}"
 RNC="$D/db-$VERSION.NC"
 #DOCS=`pwd`/../../docs_books
-DOCS=`pwd`/../../docs_books-5.0
+DOCS=`pwd`/../../docs_books-5.1
+DB_ADDONS=`pwd`/../../db_addons
 
-if [ ! -d $DOCS ]; then
-	echo "buildpkg requires a docs_books repository at the same level as
-the db repository."
+if [ ! -d $DB_ADDONS ]; then
+	echo "buildpkg requires a db_addons repository at the same level as the db repository."
 	exit 1
 fi
-
-fix_permissions()
-{
-    ROOT_DIR="$1"
-    cd $ROOT_DIR && find . -type d | xargs chmod 775
-    cd $ROOT_DIR && find . -type f | xargs chmod 444
-    cd $ROOT_DIR && chmod 664 build_windows/*vcproj
-    cd $ROOT_DIR && chmod 664 build_wince/*vcproj
-    cd $ROOT_DIR && chmod 664 build_wince/*sln
-    cd $ROOT_DIR && chmod 664 csharp/doc/libdb_dotnet*.XML
-    cd $ROOT_DIR && chmod 664 csharp/*csproj
-    cd $ROOT_DIR && chmod 664 examples_csharp/*/*.csproj
-    cd $ROOT_DIR && chmod 664 sql/jdbc/SQLite/Constants.java
-    cd $ROOT_DIR && chmod 664 sql/odbc/resource3.h
-    cd $ROOT_DIR && chmod 555 sql/odbc/conf* sql/jdbc/conf*
-    cd $ROOT_DIR/dist && sh s_perm
-}
 
 # Create directory, remove any previous release tree.
 rm -rf $R $RNC
@@ -53,54 +72,86 @@ hg archive $R
 
 echo "Created hg archive in $R"
 
-# Check that the doc repo is up to date, and create a tag if necessary.
-cd $DOCS
-hg pull -u
-if [ $? != 0 ]; then
-	echo "Failed updating the docs_books repository. Exiting."
-	rm -rf $R
-	exit 1
-fi
-has_tag=`hg tags | grep "db-${VERSION}"`
-if [ "$has_tag" = "" ]; then
-	hg tag "db-${VERSION}"
-	TAG_CREATED="true"
+if [ "$nodocs" = true ] ; then
+	rm -rf $R/docs
 else
-	hg up -r "db-${VERSION}"
+	[ -d $DOCS ] || die "buildpkg requires a docs_books repository at the same level as the db repository."
+
+	# Check that the doc repo is up to date, and create a tag if necessary.
+	cd $DOCS
+	hg pull -u
+	if [ $? != 0 ]; then
+		rm -rf $R
+		die "Failed updating the docs_books repository."
+	fi
+	has_tag=`hg tags | grep "db-${VERSION}"`
+	if [ "$has_tag" = "" ]; then
+		hg tag "db-${VERSION}"
+		TAG_CREATED="true"
+	else
+		hg up -r "db-${VERSION}"
+	fi
+
+	# Build a copy of the documentation in the release tree.
+	cd $R/dist
+	sh s_docs db-${VERSION} $DOCS
+
+	if [ $? != 0 ]; then
+		rm -rf $R
+		die "Failed generating documentation."
+	fi
+
+	# Copy in the C sharp doc.
+	if [ $CSHARP_DOC_LOCATION -eq 2 ]; then
+		scp $CSHARP_DOC_SRC .
+		CSHARP_DOC_SRC="csharp_docs.tgz"
+		if [ ! -f $CSHARP_DOC_SRC ]; then
+			echo "WARNING: Invalid csharp doc file - csharp_docs.tgz expected."
+		fi
+	fi
+	if [ $CSHARP_DOC_LOCATION -eq 0 -o ! -f $CSHARP_DOC_SRC ]; then
+		echo "WARNING: No csharp docs, skipping."
+		CSHARP_DOC_LOCATION=0
+	fi
+	if [ $CSHARP_DOC_LOCATION != 0 ]; then
+		rm -rf $R/docs/csharp
+		mkdir -p $R/docs/csharp
+		$TAR zxf $CSHARP_DOC_SRC -C $R/docs/csharp
+	fi
+
+	# Build the Java documentation.
+	cd $R/dist && sh s_javadoc
 fi
-
-# Build a copy of the documentation in the release tree.
-cd $R/dist
-sh s_docs db-${VERSION} $DOCS
-
-if [ $? != 0 ]; then
-	echo "Failed generating documentation. Exiting"
-	rm -rf $R
-	exit 1
-fi
-
-# Copy the C sharp doc from the original tree - it's not generated.
-rm -rf $R/docs/csharp
-mkdir -p $R/docs/csharp
-cp -rp $START_DIR/../docs/csharp $R/docs
 
 # Pull a copy of the JDBC and ODBC libraries into the package.
 # Tell the script where to look for packages.
-sh s_sql_drivers ../..
+cd $R/dist && sh s_sql_drivers ../../../..
 
 cd $START_DIR
 
-# Build the documentation.
-cd $R/dist && sh s_javadoc
+# Pull a copy of the bfile directory into the package.
+cd $DB_ADDONS
+hg pull -u
+if [ $? != 0 ]; then
+	echo "Failed updating the db_addons repository. Exiting."
+	rm -rf $R
+	exit 1
+fi
+
+cd $START_DIR
+SQL_EXT_DIR=$R/lang/sql/sqlite/ext
+if [ ! -d $SQL_EXT_DIR ]; then
+	mkdir -p $SQL_EXT_DIR
+fi
+if [ -d $SQL_EXT_DIR/bfile ]; then
+	rm -rf $SQL_EXT_DIR/bfile
+fi
+cp -rp $DB_ADDONS/bfile $SQL_EXT_DIR
 
 # Remove source directories we don't distribute.
-cd $R && rm -rf build_brew build_s60
-cd $R && rm -rf java/src/com/sleepycat/xa
-cd $R && rm -rf os_brew os_s60
-cd $R && rm -rf rpc_* dbinc/db_server_int.h dbinc_auto/rpc*.h
-cd $R && rm -rf test/TODO test/upgrade test/scr036 test_erlang
-cd $R && rm -rf test_perf test_purify test_repmgr
-cd $R && rm -rf test_server test_stl test_vxworks
+cd $R && rm -rf test/tcl/TODO test/upgrade test/scr036 test/erlang
+cd $R && rm -rf test/perf test/purify test/repmgr
+cd $R && rm -rf test/server test/stl test/vxworks
 cd $R && find . -name '.hg*' | xargs rm -f
 cd $R && find . -name 'tags' | xargs rm -f
 
@@ -123,13 +174,14 @@ cd $R && find . -name 'tags' | xargs rm -f
 # Remove the build directory
 ### cd $R && rm -rf build_run
 
-fix_permissions $R
+(cd $R/dist && ./s_perm)
 
 # Check for file names differing only in case.
 cd $R && find . | sort -f | uniq -ic | sed '/1 /d'
 
 # Create the crypto tar archive release.
 T="$D/db-$VERSION.tar.gz"
+rm -f $T
 cd $D && $TAR czf $T -find db-$VERSION -chown 100 -chgrp 100
 chmod 444 $T
 
@@ -137,10 +189,11 @@ chmod 444 $T
 cd $D && mv -i db-$VERSION $RNC && $TAR xzf $T
 cd $RNC/dist && sh s_crypto
 
-fix_permissions $RNC
+(cd $RNC/dist && ./s_perm)
 
 # Create the non-crypto tar archive release.
 T="$D/db-$VERSION.NC.tar.gz"
+rm -f $T
 cd $RNC/.. && $TAR czf $T -find db-$VERSION.NC -chown 100 -chgrp 100
 chmod 444 $T
 
@@ -152,11 +205,13 @@ cd $RNC && awk '{print $0 "\r"}' < README > $t && rm -f README && cp $t README &
 
 # Create the crypto zip archive release.
 T="$D/db-$VERSION.zip"
+rm -f $T
 cd $R/.. && rm -f $T && zip -q -r $T db-$VERSION
 chmod 444 $T
 
 # Create the non-crypto zip archive release.
 T="$D/db-$VERSION.NC.zip"
+rm -f $T
 cd $RNC/.. && rm -f $T && zip -q -r $T db-$VERSION.NC 
 chmod 444 $T
 
diff --git a/dist/s_sql_drivers b/dist/s_sql_drivers
--- a/dist/s_sql_drivers
+++ b/dist/s_sql_drivers
@@ -7,16 +7,33 @@
 # in the parent of this repository/source tree.
 
 # The packages can be downloaded from (update to current version):
-# http://www.ch-werner.de/sqliteodbc/sqliteodbc-0.85.tar.gz
-# http://www.ch-werner.de/javasqlite/javasqlite-20100131.tar.gz
+# http://www.ch-werner.de/sqliteodbc/sqliteodbc-0.86.tar.gz
+# http://www.ch-werner.de/javasqlite/javasqlite-20100727.tar.gz
+die()
+{
+	echo >&2 "$@"
+	exit 1
+}
 
-if [ "$1x" != "x" ]; then
+START_DIR=`pwd`
+if [ "x$1" != "x" ]; then
 	PKG_ROOT=$1
 else
-	PKG_ROOT=.
+	PKG_ROOT=../..
 fi
-ODBC_PACKAGE=`ls $PKG_ROOT/../../sqliteodbc-*.tar.gz | tail -1`
-JDBC_PACKAGE=`ls $PKG_ROOT/../../javasqlite-*.tar.gz | tail -1`
+
+#DB_ADDONS_REPO=$PKG_ROOT/db_addons
+#if [ ! -d $DB_ADDONS_REPO ]; then
+#	die "db_addons repository doesn't exist."
+#fi
+#cd $DB_ADDONS_REPO
+#hg pull -u
+#if [ $? != 0 ]; then
+#	die "Failed updating the db_addons repository."
+#fi
+cd $START_DIR
+ODBC_PACKAGE=`ls $PKG_ROOT/sqliteodbc-0.86.tar.gz | tail -1`
+JDBC_PACKAGE=`ls $PKG_ROOT/javasqlite-20100727.tar.gz | tail -1`
 
 if [ ! -e $ODBC_PACKAGE ]; then
 	echo "No ODBC package found, can't continue."
@@ -29,11 +46,11 @@ if [ ! -e $JDBC_PACKAGE ]; then
 	exit 1
 fi
 
-SQL_DIR=../sql/
+SQL_DIR=../lang/sql/
 ODBC_DIR=$SQL_DIR/odbc
 JDBC_DIR=$SQL_DIR/jdbc
-mkdir -p $ODBC_DIR
-mkdir -p $JDBC_DIR
+rm -rf "$ODBC_DIR" && mkdir -p $ODBC_DIR
+rm -rf "$JDBC_DIR" && mkdir -p $JDBC_DIR
 
 HOMEDIR=`pwd`
 
@@ -72,39 +89,25 @@ rm -rf $JDBC_DIR/debian $ODBC_DIR/*ming* $ODBC_DIR/README.* $ODBC_DIR/*mak
 
 # Patch the JDBC and ODBC build files for autoconf, so the Berkeley DB library
 # can be added to the link command.
-
-echo "
---- Makefile.in 
-+++ Makefile.in
-50c50
-< LIBS=	@SQLITE_LIB@ @SQLITE3_LIB@
----
-> LIBS=	@SQLITE_LIB@ @SQLITE3_LIB@ @LDFLAGS@" > s_sql_drivers.tmpdiff
-
-( cd ../sql/jdbc && patch < ../../dist/s_sql_drivers.tmpdiff)
-
-echo "
---- Makefile.in 
-+++ Makefile.in
-30c30
-< ODBC_LIB =	@ODBC_LIB@
----
-> ODBC_LIB =	@ODBC_LIB@ @LDFLAGS@" > s_sql_drivers.tmpdiff
-
-( cd ../sql/odbc && patch < ../../dist/s_sql_drivers.tmpdiff)
-rm -f s_sql_drivers.tmpdiff
+mv $JDBC_DIR/Makefile.in $JDBC_DIR/Makefile.in.tmp
+# 1. Define BDB_LIB for Makefile
+# 2. Add LD_LIBRARY_PATH for runing native/mkconst in JDBC configuration
+cat $JDBC_DIR/Makefile.in.tmp | \
+        sed -e '/native\/mkconst > SQLite\/Constants.java/ i \\t\LD_LIBRARY_PATH=\"\$\$LD_LIBRARY_PATH:\$(PWD)\/..\/.libs\" \\' \
+            -e '/^LIBS=/s/$/ @BDB_LIB@/' > $JDBC_DIR/Makefile.in
+rm -f $JDBC_DIR/Makefile.in.tmp
 
 # Generate the resource3.h file needed by ODBC on Windows.
-VERS=`cat ../sql/odbc/VERSION`
+VERS=`cat $ODBC_DIR/VERSION`
 VERS_C=`echo $VERS | sed -e 's/\([0-9]\+\)[.]\([0-9]\+\).*/\1,\2/g'`
-cat ../sql/odbc/resource.h.in | sed -e "s/--VERS_C--/$VERS_C/g" -e "s/--VERS--/$VERS/g" > ../sql/odbc/resource3.h
+cat $ODBC_DIR/resource.h.in | sed -e "s/--VERS_C--/$VERS_C/g" -e "s/--VERS--/$VERS/g" > $ODBC_DIR/resource3.h
 
-# Let sqlite3odb.rc include "../sql/generated/sqlite3.h" instead of sqlite3.h 
-mv ../sql/odbc/sqlite3odbc.rc ../sql/odbc/sqlite3odbc.rc.in
-cat ../sql/odbc/sqlite3odbc.rc.in | sed -e 's/sqlite3.h/..\/sql\/generated\/sqlite3.h/g' > ../sql/odbc/sqlite3odbc.rc
+# Let sqlite3odb.rc include "$SQL_DIR/generated/sqlite3.h" instead of sqlite3.h 
+mv $ODBC_DIR/sqlite3odbc.rc $ODBC_DIR/sqlite3odbc.rc.in
+cat $ODBC_DIR/sqlite3odbc.rc.in | sed -e 's/sqlite3.h/..\/lang\/sql\/generated\/sqlite3.h/g' > $ODBC_DIR/sqlite3odbc.rc
 
 # Generate Constants.java needed by JDBC on Windows
-gcc -DHAVE_SQLITE3 -I../sql/generated -o mkconst ../sql/jdbc/native/mkconst.c
+gcc -DHAVE_SQLITE3 -I$SQL_DIR/generated -o mkconst $JDBC_DIR/native/mkconst.c
 ./mkconst > $JDBC_DIR/SQLite/Constants.java
 
 # Add the wildcard below since gcc on Windows appends a .exe
diff --git a/dist/s_windows_dsp b/dist/s_windows_dsp
--- a/dist/s_windows_dsp
+++ b/dist/s_windows_dsp
@@ -1,241 +1,297 @@
 #!/bin/bash -
 #	$Id$
 #
-# Build Windows .dsp files.
-# Build Windows Mobile .dsp and .vcproj files
+# Build Windows CE .vcproj files
 # Build Windows .vcproj files.
 
 . ./RELEASE
 
-SRCFILES=srcfiles.in
-
-create_dsp()
+create_projects()
 {
-    projname="$1"       # name of the .dsp file
-    match="$2"          # the string used to egrep the $sources file
-    sources="$3"        # a modified version of $SRCFILES to facilitate matches
-    dsptemplate="$4"    # overall template file for the .dsp
-    extra_cppflags="$5" # extra flags to send to compiler
-    extra_debug_cppflags="$6" # Flags only used for debug builds
-    release_libs="$7"   # libraries to link against in Release builds
-    debug_libs="$8"     # libraries to link against in Debug builds
-    lib_suffix="$9"     # the library name is libdb@lib_suffix@@VERSION@
-    proj_type="${10}"	# the project type dsp or vcp
-    proj_guid="${11}"	# The project guid for VS2005 projects
-    extra_includes="${12}"	# Additional include paths.
-    mod_def="${13}"	# Dynamic library module definition file name
+    # project name list
+    PROJECTS=$1
 
-    # Set the default project type to be "dsp"
-    if [ ! "$proj_type" ] ; then
-	    proj_type=dsp
-    fi
+    # xquery script template
+    TEMPLATE=genproject.template
 
-			# template file for the src file fragments
-    srctemplate="$BUILDDIR/srcfile_$proj_type.src"
-    rsrctemplate="$BUILDDIR/rsrcfile_$proj_type.src"
-    dspoutput=$BUILDDIR/$projname.$proj_type
+    # temporary script, post-sed-replacement
+    TEMP_SCRIPT=genproject.script
 
-    rm -f $dspoutput.insert
-    for srcpath in `egrep "$match" $sources | sed -e 's/[ 	].*//'`
-    do
-        # take the path name and break it up, converting / to \\.
-        # so many backslashes needed because of shell quoting and
-        # sed quoting -- we'll end up with two backslashes for every
-        # forward slash, but we need that when feeding that to the
-        # later sed command.
-        set - `echo $srcpath | sed -e 's;\(.*\)/;../\\1 ;' \
-            -e "s;$BUILDDIR;.;" \
-            -e 's;/;\\\\\\\\;g'`
-	srcdir="$1"
-	srcfile="$2"
-	if [ "${srcfile##*.}" = "rc" -a "$proj_type" = "vcproj" ] ; then
-		inptemplate=$rsrctemplate
-	else
-		inptemplate=$srctemplate
-	fi
+    # xml document input template
+    CONFIG_INPUT=$2
 
-        sed -e "s/@srcdir@/$srcdir/g" \
-            -e "s/@srcfile@/$srcfile/g" \
-            < $inptemplate >> $dspoutput.insert
-    done
-    sed -e "/@SOURCE_FILES@/r$dspoutput.insert" \
-        -e "/@SOURCE_FILES@/d" \
-        -e "s/@project_name@/$projname/g" \
-        -e "s,@extra_cppflags@,$extra_cppflags,g" \
-	-e "s,@extra_debug_cppflags@,$extra_cppflags\;$extra_debug_cppflags,g" \
-        -e "s,@extra_includes@,$extra_includes,g" \
-        -e "s,@release_libs@,$release_libs,g" \
-        -e "s,@debug_libs@,$debug_libs,g" \
-        -e "s,@lib_suffix@,$lib_suffix,g" \
-        -e "s/@DB_VERSION_MAJOR@/$DB_VERSION_MAJOR/g" \
+    # temporary xml document, post-sed-replacement
+    CONFIG_OUTPUT=projects.xml
+
+    # location for output project files
+    PROJECT_OUTPUT_DIR=$3
+
+    # substitute some variables in the XML document template
+    sed -e "s/@DB_VERSION_MAJOR@/$DB_VERSION_MAJOR/g" \
         -e "s/@DB_VERSION_MINOR@/$DB_VERSION_MINOR/g" \
-        -e "s/@PROJ_GUID@/$proj_guid/g" \
-	-e "s,@MOD_DEF@,$mod_def,g" \
-      < $dsptemplate > $dspoutput.new
+        < $CONFIG_INPUT > $CONFIG_OUTPUT
 
-    # We run this script on Windows (under Cygwin).  Fix up the line-endings
-    # for the temporary files.  We don't test the platform, just run unix2dos
-    # if the command exists, ignoring any not-found error message.
-    (unix2dos.exe $dspoutput.new) >/dev/null 2>&1
+    # for each project, substitute 2 variables in the XQuery script, then run it
+    for v in VC8
+    do
+        if [ $v = "VC7.1" ]; then
+            VERSION="7.10"
+        else
+    	    VERSION="8.00"
+        fi
 
-    # Set the file mode to 644 because the VC++ IDE needs a writeable file
-    # in our development environment.
-    cmp $dspoutput.new $dspoutput > /dev/null 2>&1 ||
-	(echo "Building $dspoutput" && rm -f $dspoutput &&
-	    cp $dspoutput.new $dspoutput && chmod 664 $dspoutput)
-    rm -f $dspoutput.insert $dspoutput.new
+        echo "Building for Visual Studio version $VERSION"
+
+        for i in `cat $PROJECTS`
+        do
+            sed -e "s!@PROJECT_NAME@!$i!g" -e "s!@PROJECT_INPUT@!$CONFIG_OUTPUT!g" -e "s!@VISUAL_STUDIO_VERSION@!$VERSION!g" < $TEMPLATE > $TEMP_SCRIPT
+            TMP=$PROJECT_OUTPUT_DIR/$i.tmp.vcproj
+            if [ $v = "VC7.1" ]; then
+                TARG=$PROJECT_OUTPUT_DIR/${i}_vs71.vcproj
+            else
+                TARG=$PROJECT_OUTPUT_DIR/${i}.vcproj
+            fi
+            xqilla -o $TMP $TEMP_SCRIPT
+            rm -f $TEMP_SCRIPT
+            chmod 644 $TMP
+            cmp $TMP $TARG > /dev/null 2>&1 ||
+            (echo "Building $TARG" && rm -f $TARG &&
+            cp $TMP $TARG)
+            rm -f $TMP
+        done
+    done
+
+    # Cleanup.
+    rm -f $CONFIG_OUTPUT
 }
 
-TMPA=/tmp/swindsp$$a
-trap "rm -f $TMPA; exit 1" 1 2 3 15
+create_projects_csharp()
+{
+    # project name list
+    PROJECTS=$1
 
-# create a copy of the srcfiles with comments and empty lines removed.
-# add a space at the end of each list of modules so that each module
-# can be unambiguously matched e.g. ' dynamic '
-sed -e "s/#.*$//" \
-    -e "/^[ 	]*$/d" \
-    -e "s/[ 	][ 	]*/ /" \
-    -e "s/[ 	]*$//" \
-    -e "/[	 ]/!d" \
-    -e "s/$/ /" < $SRCFILES > $TMPA
+    # xquery script template
+    TEMPLATE=genproject_csharp.template
 
-# get a list of all modules mentioned
-#
-MODULES="`sed -e 's/^[^	 ]* //' < $TMPA | tr ' ' '\012' | sort | uniq`"
+    # temporary script, post-sed-replacement
+    TEMP_SCRIPT=genproject.script
 
-for module in $MODULES
-do
-    case "$module" in
-    ce)
-	BUILDDIR=../build_wince
-	# Build VS2005 projects.
-	# The GUID passed in must match that in the .sln workspace.
-	# It would be ideal to grab the GUID from there if this
-	# project is already included there.
-        create_dsp db_static " $module " $TMPA \
-	    ../build_wince/static_vcproj.src '' '' '' '' '' vcproj \
-	    "4AB4958F-8DD0-49B5-8C02-014B5637C59A"
-        ;;
-    ce_small)
-	BUILDDIR=../build_wince
-	# Build VS2005 projects.
-	# The GUID passed in must match that in the .sln workspace.
-	# It would be ideal to grab the GUID from there if this
-	# project is already included there.
-        create_dsp db_small_static " $module " $TMPA  \
-            ../build_wince/static_vcproj.src 'HAVE_SMALLBUILD' '' \
-	    '' '' _small vcproj "6A2849DA-8F7C-4B50-BDAE-AE7752EF8213"
-        ;;
-    ce_sql)
-	BUILDDIR=../build_wince
-	# Build VS2005 projects.
-	# The GUID passed in must match that in the .sln workspace.
-	# It would be ideal to grab the GUID from there if this
-	# project is already included there.
-	SQL_DEFINES="SQLITE_EXPORTS;SQLITE_CORE;SQLITE_THREADSAFE=1;BDBSQL_OMIT_SHARING"
-	SQL_DEBUG_DEFINES="SQLITE_TEST;SQLITE_DEBUG;SQLITE_MEMDEBUG"
-        create_dsp db_sql " $module " $TMPA  \
-            ../build_wince/dynamic_vcproj.src \
-	    "$SQL_DEFINES" "$SQL_DEBUG_DEFINES" \
-	    '' '' _sql vcproj "ACE41B30-04BB-11DF-8A39-0800200C9A66" \
-	    "../sql/sqlite/src;../sql/adapter;../sql/generated;../build_windows" \
-	    "../build_windows/libdb_sql.def"
-        ;;
-    app=wce_tpcb )
-        appname=`echo $module | sed -e 's/^app=//'`
-	BUILDDIR=../build_wince
-	# The GUID passed in must match that in the .sln workspace.
-	# It would be ideal to grab the GUID from there if this
-	# project is already included there.
-	create_dsp $appname " $module " $TMPA \
-	    ../build_wince/app_vcproj.src '__NO_SYSTEM_INCLUDES' '' \
-	    '' '' '' vcproj "F2CE670A-ABAE-414A-9A17-8079AB58613F"
-	;;
-    app=wce_sql )
-        appname=`echo $module | sed -e 's/^app=//'`
-	BUILDDIR=../build_wince
-	SQL_LIB_NAME="libdb_sql${DB_VERSION_MAJOR}${DB_VERSION_MINOR}"
-	SQL_DEFINES="POCKETPC2003_UI_MODEL"
-	create_dsp $appname " $module " $TMPA \
-	    ../build_wince/app_vcproj.src "$SQL_DEFINES" '' \
-	    "$SQL_LIB_NAME.lib" "${SQL_LIB_NAME}d.lib" '' vcproj \
-	    "4BF83E5F-2DF4-4C94-97FB-700BA475BB4F" "../sql/generated"
-	;;
-    android|brew|s60|vx|vxsmall|vx6 )
-        ;;
-    * )
-        echo \
-    "s_windows_dsp: module name $module in $SRCFILES is unknown type"
-        ;;
-    esac
-done
+    # xml document input template
+    CONFIG_INPUT=$2
 
-rm -f $TMPA
+    # temporary xml document, post-sed-replacement
+    CONFIG_OUTPUT=projects.xml
 
-#
-# Drive construction of Visual Studio (version 7.1) projects 
-# files, using an xquery script (genproject.template),an input XML
-# document, and a file containing a list of project names.
-#
+    # substitute some variables in the XML document template
+    sed -e "s/@DB_VERSION_MAJOR@/$DB_VERSION_MAJOR/g" \
+        -e "s/@DB_VERSION_MINOR@/$DB_VERSION_MINOR/g" \
+        < $CONFIG_INPUT > $CONFIG_OUTPUT
 
-# Source the Berkeley DB release version numbers.
-cd win_projects
-
-# project name list
-PROJECTS=db.projects
-
-# xquery script template, called genproject.template in DBXML tree.
-TEMPLATE=genproject.template
-
-# temporary script, post-sed-replacement
-TEMP_SCRIPT=genproject.script
-
-# xml document input template, called dbxml.template.xml in DBXML tree.
-CONFIG_INPUT=projects.template.xml
-
-# temporary xml document, post-sed-replacement, called dbxml.projects in DBXML
-CONFIG_OUTPUT=projects.xml
-
-# location for output project files
-PROJECT_OUTPUT_DIR=../../build_windows
-
-# substitute some variables in the XML document template
-sed -e "s/@DB_VERSION_MAJOR@/$DB_VERSION_MAJOR/g" \
-    -e "s/@DB_VERSION_MINOR@/$DB_VERSION_MINOR/g" \
-    < $CONFIG_INPUT > $CONFIG_OUTPUT
-
-echo "Building Visual Studio project files -- "
-echo "   output only for modified projects (this can take a while)"
-
-# for each project, substitute 2 variables in the XQuery script, then run it
-for v in VC8
-do
-    if [ $v = "VC7.1" ]; then
-	VERSION="7.10"
-    else
-	VERSION="8.00"
-    fi
-
-    echo "Building for Visual Studio version $VERSION"
-
+    # for each project, substitute 2 variables in the XQuery script, then run it
     for i in `cat $PROJECTS`
     do
-	sed -e "s!@PROJECT_NAME@!$i!g" -e "s!@PROJECT_INPUT@!$CONFIG_OUTPUT!g" -e "s!@VISUAL_STUDIO_VERSION@!$VERSION!g" < $TEMPLATE > $TEMP_SCRIPT
-	TMP=$PROJECT_OUTPUT_DIR/$i.tmp.vcproj
-	if [ $v = "VC7.1" ]; then
-	    TARG=$PROJECT_OUTPUT_DIR/${i}_vs71.vcproj
-	else
-	    TARG=$PROJECT_OUTPUT_DIR/${i}.vcproj
-	fi
-	xqilla -o $TMP $TEMP_SCRIPT
-	rm -f $TEMP_SCRIPT
-	cmp $TMP $TARG > /dev/null 2>&1 ||
-	(echo "Building $TARG" && rm -f $TARG &&
-	    cp $TMP $TARG && chmod 664 $TARG)
-	rm -f $TMP
-    done
-done
+        # Split project path into dir + basename
+        PROJECT_OUTPUT_DIR=`dirname $i`
+        i=`basename $i`
 
-# Cleanup.
-rm -f $CONFIG_OUTPUT
+        sed -e "s!@PROJECT_NAME@!$i!g" -e "s!@PROJECT_INPUT@!$CONFIG_OUTPUT!g" -e "s!@VISUAL_STUDIO_VERSION@!$VERSION!g" < $TEMPLATE > $TEMP_SCRIPT
+        TMP=$PROJECT_OUTPUT_DIR/$i.tmp.csproj
+        TARG=$PROJECT_OUTPUT_DIR/${i}.csproj
+        xqilla -o $TMP $TEMP_SCRIPT
+        rm -f $TEMP_SCRIPT
+        chmod 644 $TMP
+        cmp $TMP $TARG > /dev/null 2>&1 ||
+        (echo "Building $TARG" && rm -f $TARG &&
+        cp $TMP $TARG)
+        rm -f $TMP
+    done
+
+    # Cleanup.
+    rm -f $CONFIG_OUTPUT
+}
+
+cd win_projects
+
+# Create/Update Windows project files
+echo "Building Visual Studio project files for Windows -- "
+echo "   output only for modified projects (this can take a while)"
+create_projects db.projects projects.template.xml ../../build_windows
+
+# Create/Update Windows CE project files
+echo "Building Visual Studio project files for Windows CE -- "
+echo "   output only for modified projects (this can take a while)"
+create_projects db_wince.projects projects_wince.template.xml ../../build_wince
+
+# Create/Update C Sharp project files
+echo "Building C Sharp project files -- "
+echo "   output only for modified projects (this can take a while)"
+create_projects_csharp db_csharp.projects projects_csharp.template.xml
+
 cd ..
+
+upgrade_solution(){
+	fail=0
+	cp -f $1.sln $1.sln.pre
+	# Delete all the vs2010 project files to avoid a popup window
+	rm -fr *.vcxproj 2>/dev/null
+	echo "Upgrading $1.sln ....."
+	echo "call \"${VS10TOOLSDIR}\"vsvars32.bat" > $tmp_bat
+	echo "devenv $1.sln /upgrade" >> $tmp_bat
+	cmd /c $tmp_bat >/dev/null 2>/dev/null || fail=1
+	if test "$fail" = "1"; then
+		echo "	Fail to upgrade $1.sln !"
+		fail=0
+	fi
+	# Save those vs2010 projects
+	cp -f *.vcxproj $vcxproj_tmp_dir 2>/dev/null
+	mv -f $1.sln $1_vs2010.sln
+	mv -f $1.sln.pre $1.sln
+	return 0
+}
+
+convert_vsfiles(){
+
+	VS10TOOLSDIR=`cygpath -m "$VS100COMNTOOLS"`
+	vcxproj_tmp_dir="../vs2010_projects"
+	tmp_bat="_vs2010_tmp1.bat"
+	fail=0
+
+	mkdir -p $vcxproj_tmp_dir
+
+	cs_project_files="../lang/csharp/src/db_dotnet.csproj \
+	    ../examples/csharp/excs_access/excs_access.csproj \
+	    ../examples/csharp/excs_btrec/excs_btrec.csproj \
+	    ../examples/csharp/excs_env/excs_env.csproj \
+	    ../examples/csharp/excs_sequence/excs_sequence.csproj \
+	    ../examples/csharp/excs_repquote/excs_repquote.csproj \
+	    ../test/csharp/DotNetTest.csproj \
+	    ../examples/csharp/excs_txn/excs_txn.csproj"
+
+	# Save the csharp project files
+	for f in $cs_project_files;do
+		cp -f $f $f.bak
+	done
+
+	# Upgrade the BDB_dotNet_examples.sln
+	upgrade_solution BDB_dotNet_examples
+
+	# Upgrade the BDB_dotNet.sln
+	upgrade_solution BDB_dotNet
+
+	# Restore the csharp project files
+	for f in $cs_project_files;do
+		mv -f $f.bak $f
+	done
+
+	# Upgrade Berkeley_DB_examples.sln
+	upgrade_solution Berkeley_DB_examples
+
+	# Upgrade the Berkeley_DB.sln
+	upgrade_solution Berkeley_DB
+
+	# Upgrade all those unchanged projects
+	# Copy all the vs2010 projects back
+	cp -f $vcxproj_tmp_dir/*.vcxproj .
+	list="`ls *.vcproj`"
+	for proj in $list;do
+		# Skip upgrading excxx_wce_sql.vcproj
+		test "$proj" = "excxx_wce_sql.vcproj" && continue
+		name="`echo $proj| sed 's/\.vcproj//g'`"
+		if test -f "$name.vcxproj"; then
+			# The project has been converted
+			continue
+		else
+			echo "Upgrading $proj ....."
+			echo "call \"${VS10TOOLSDIR}\"vsvars32.bat" > $tmp_bat
+			echo "devenv $proj /upgrade" >> $tmp_bat
+			cmd /c $tmp_bat >/dev/null 2>/dev/null || fail=1
+			if test "$fail" = "1"; then
+				echo "	Fail to upgrade $proj !"
+				fail=0
+			fi
+
+		fi
+	done
+
+	# Delete those temporary/backup/upgardelog directories/files.	
+	for f in $cs_project_files;do
+		rm -f $f.old
+		rm -f $f.user
+	done	
+	rm -f "$tmp_bat"
+	rm -fr "$vcxproj_tmp_dir"
+	rm -fr Backup*
+	rm -f *.user
+	rm -f UpgradeLog*.XML
+	rm -f *.suo
+	rm -f *.sdf
+	rm -f *.ncb
+	rm -f *.old
+	rm -fr "_UpgradeReport_Files"
+	rm -fr Win32
+	rm -fr x64
+	rm -fr AnyCPU
+}
+
+process_vcxproj(){
+	names=""
+	win32de_name=""
+	x64de_name=""
+	win32rel_name=""
+	x64rel_name=""
+	ext=""
+	list="`ls *.vcxproj`"
+	
+	for proj in $list;do
+		echo "Processing project $proj ...."
+		names="`sed -n '/<OutputFile>/p' $proj | sed 's#</*OutputFile>##g' | sed 's#\$(.*)##g' | sort | uniq`"
+		names_len="`sed -n '/<OutputFile>/p' $proj | sed 's#</*OutputFile>##g' | sed 's#\$(.*)##g' | sort | uniq | wc -l`"
+		name="`echo $names|awk '{print $1}'`"
+		test "$names_len" = "1" || name="`echo $name| sed 's#d\.#.#g'`"
+		pre_name="`echo $name|  sed 's/\(.*\)\.[^.]*/\1/g'`"
+		ext_name="`echo $name|  sed 's/.*\(\.[^.]*\)/\1/g'`"
+		win32rel_name="$pre_name"
+		x64rel_name="$pre_name"
+		ext="$ext_name"
+		if test "$names_len" = "1"; then
+			win32de_name="$pre_name"
+			x64de_name="$pre_name"
+		else
+			win32de_name="${pre_name}d"
+			x64de_name="${pre_name}d"
+		fi
+		cat /dev/null >1.tmp
+		echo "    <TargetName Condition=\"'\$(Configuration)|\$(Platform)'=='Debug|x64'\">$x64de_name</TargetName>" >>1.tmp
+		echo "    <TargetExt Condition=\"'\$(Configuration)|\$(Platform)'=='Debug|x64'\">$ext</TargetExt>" >>1.tmp
+		echo "    <TargetName Condition=\"'\$(Configuration)|\$(Platform)'=='Release|x64'\">$x64rel_name</TargetName>" >>1.tmp
+		echo "    <TargetExt Condition=\"'\$(Configuration)|\$(Platform)'=='Release|x64'\">$ext</TargetExt>" >>1.tmp
+		echo "    <TargetName Condition=\"'\$(Configuration)|\$(Platform)'=='Debug|Win32'\">$win32de_name</TargetName>" >>1.tmp
+		echo "    <TargetExt Condition=\"'\$(Configuration)|\$(Platform)'=='Debug|Win32'\">$ext</TargetExt>" >>1.tmp
+		echo "    <TargetName Condition=\"'\$(Configuration)|\$(Platform)'=='Release|Win32'\">$win32rel_name</TargetName>" >>1.tmp
+		echo "    <TargetExt Condition=\"'\$(Configuration)|\$(Platform)'=='Release|Win32'\">$ext</TargetExt>" >>1.tmp
+		echo "  </PropertyGroup>" >>1.tmp
+		sed 's#.*<OutputFile>.*#	<OutputFile>$(OutDir)$(TargetName)$(TargetExt)</OutputFile>#g' $proj | \
+		sed '/UserMacros/ {
+			:la
+			n
+			/<\/PropertyGroup>/ {
+				s/.*//g
+				r 1.tmp
+				b
+			}
+			b la	
+	
+		}' | sed '/^$/d' >2.tmp
+		# mv $proj $proj.bak
+		mv -f 2.tmp $proj
+		rm -f 1.tmp
+	done
+}
+
+# Build vs2010 solution files and project files.
+if test "$1" = "-vs2010"; then
+	cd ../build_windows
+	convert_vsfiles
+	process_vcxproj
+	cd ../dist
+fi
